### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by egor-rusnak** [egor-rusnak/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by ydRusnak** [comment]
<h3>EXPIRIENCE</h3>
<h6>RECENT</h6>
<ul class="timeline">
<li>
  <p class="date">2018</p>
  <p>
    Amongst many fighters of the past was featured in the movie 
    <a href="https://en.wikipedia.org/wiki/Ready_Player_One_(film)" rel="external"><q>Ready Player One</q></a>. Ryu ready always!
  </p>
</li>
<li>  
  <p class="date">2017</p>
  <p>
    United with unknown until then to me 
    <a href="https://en.wikipedia.org/wiki/Power_Rangers:_Battle_for_the_Grid" rel="external">Power Rangers</a> 
    to defea resurrected <a href="https://streetfighter.fandom.com/wiki/M._Bison" rel="external">M.Bison</a>.
    Damn good fighters they are, even not knowing karate ways!</p>
</li>
<li>  
  <p class="date">2016</p>
  <p>In <a href="https://en.wikipedia.org/wiki/Street_Fighter_V" rel="external"><q>Street Fighter V</q></a> 
    once and for all erased <a href="https://streetfighter.fandom.com/wiki/M._Bison" rel="external">M.Bison</a> 
    from earth and tamed my inner <a href="https://streetfighter.fandom.com/wiki/Evil_Ryu" rel="external">Evil Ryu</a>. 
    Also spent some time on a side-project, mini-series <a href="https://en.wikipedia.org/wiki/Street_Fighter:_Resurrection" rel="external"><q>Street Fighter: Resurrection</q></a>.</p>
</li>
</ul>
<h6>BACK THEN</h6>
<ul class="timeline">
<li>  
  <p class="date">2014</p>
  <p>Filmed in a martial arts tutorial <a href="https://en.wikipedia.org/wiki/Street_Fighter:_Assassin%27s_Fist" rel="external"><q>Street Fighter: Assassin's Fist</q></a>, revealing to audience forgotten art of Ansatsuken.</p>
</li>
<li>  
  <p class="date">2012</p>
  <p>The gods of intenet concluded me in the animated movie <a href="https://en.wikipedia.org/wiki/Wreck-It_Ralph" rel="external"><q>Wreck-It Ralph</q></a>, but rewarded me with a good drink for it!</p>
</li>
<li>  
  <p class="date">2008</p>
  <p>My evil alter ego sneaked out of control and became a boss in <a href="https://streetfighter.fandom.com/ru/wiki/Street_Fighter_IV" rel="external"><q>Street Fighter IV</q></a>.</p>
</li>
<li>  
  <p class="date">2006</p>
  <p>Borrowed my famous ripped gi to <a href="https://onimusha.fandom.com/wiki/Hideyasu_Y%C5%ABki" rel="external">Soki</a> in <a href="https://en.wikipedia.org/wiki/Onimusha:_Dawn_of_Dreams" rel="external"><q>Onimusha: Dawn of Dreams</q></a>, gods informed me he needed that for the battle.</p>
</li>
</ul>
<h6>PAST CENTURY</h6>
<ul class="timeline">
<li class="details">
  <input type="checkbox" id="1998">
  <label for="1998" class="summary"><span class="date">1998</span> - <q>Street Fighter Alpha 2</q> and Marvel</p></label>
  <div>
    <ol>
      <li>
        <p>Defeated <a href="https://streetfighter.fandom.com/wiki/M._Bison" rel="external">M.Bison</a>  in <a href="https://en.wikipedia.org/wiki/Street_Fighter_Alpha_2" rel="external"><q>Street Fighter Alpha 2</q></a>, 
        bastard wanted to use my heroic body for his evil intentions, but retreated with shame.</p>
      </li>
      <li>
        <p>Also this year I encountered Marvel universe in 
          <a href="https://en.wikipedia.org/wiki/Marvel_vs._Capcom:_Clash_of_Super_Heroes" rel="external"><q>Marvel vs. Capcom: Clash of Super Heroes</q></a> 
          fighter, loyal to my employer, <a href="https://www.capcom.com/" rel="external">Capcom</a>, of course.</p></li>
    </ol>
  </div>
</li>
<li class="details">
  <input type="checkbox" id="1997">
  <label for="1997" class="summary"><span class="date">1997</span> - <q>Street Fighter III</q> and <q>Street Fighter EX</q></p></label>
  <div>
    <ol>
      <li>
        <p>Reunited with Ken, my friend and opponent in <a href="" rel="external"><q>Street Fighter III</q></a>. Men's friendship works mysteriously.</p>
      </li>
      <li><p>Also helped with Arika project <a href="https://en.wikipedia.org/wiki/Street_Fighter_EX" rel="external"><q>Street Fighter EX</q></a></p></li>
    </ol>
  </div>
</li>
<li class="details">
  <input type="checkbox" id="1996">
  <label for="1996" class="summary"><span class="date">1996</span> - AKUMA in <q>Street Fighter Alhpa 2</q> and I in <q>Super Puzzle Fighter II Turbo</q></p></label>
  <div>
    <ol>
      <li>
        <p>Took care of villainous Akuma in <a href="https://en.wikipedia.org/wiki/Street_Fighter_Alpha_2" rel="external"><q>Street Fighter Alpha 2</q></a>.</p>
      </li>
      <li><p> As a freelance on <a href="https://en.wikipedia.org/wiki/Super_Puzzle_Fighter_II_Turbo" rel="external"><q>Super Puzzle Fighter II Turbo</q></a> tried myself in a new genre, puzzle games. Let the wrath of seven heavens come upon these malicious enigmas, never again!</p>
      </li>
    </ol>
  </div>
</li>
<li>  
  <p>1995</p>
  <p>Kept fighting in <a href="https://en.wikipedia.org/wiki/Street_Fighter_Alpha" rel="external"><q>Street Fighter Alpha: Warriors' Dreams"</q></a>.</p>
</li>
<li>  
  <p class="date">1994</p>
  <p>Screened in a movie <a href="https://en.wikipedia.org/wiki/Street_Fighter_(video_game)" rel="external"><q>Street Fighter</q></a>, so that the batllesof past would not be forgotten by millenial generation.</p>
</li>
<li>  
  <p class="date">1991</p>
  <p>Was promoted to <a href="https://en.wikipedia.org/wiki/Street_Fighter_II" rel="external"><q>Street Fighter II</q></a>. Didn't stay there for long, celebrations and office dwelling is not for me!</p>
</li>
<li>  
  <p class="date">1987</p>
  <p>Started working for <a href="https://www.capcom.com/" rel="external">Capcom</a> project <a href="https://en.wikipedia.org/wiki/Street_Fighter_(video_game)" rel="external"><q>Street Fighter</q></a>. My partner was <a href="https://streetfighter.fandom.com/wiki/Ken_Masters" rel="external">Ken Masters</a>, the boss'name was Sagat.</p>
</li>
</ul>

**Comment by egor-rusnak** [comment]
WP 💯
